### ISSUE TITLE
About KL divergence derivation

### ISSUE THREAD

**Issue by lvXiangwei** [fannie1208/CaNet#1]
Thank you for your valuable work. I have a small question about the derivation of the KL divergence.From my perspective, it appears as $\pi_{kv}^{(l)}\log\pi_{kv}^{(l)}+\pi_{kv}^{(l)}\log K$.

**Comment by qitianwu** [comment]
Hi Xiangwei,

We use the empirical estimation for computing the KL divergence where the expectation is estimated by observed samples, which gives rise to Eqn. 11 in our paper.
